- game.c
Added my name alongside my room to the game.
> Add: omar with room 61

- game.c
> Add: Jacob with room 11

- game.c
Added my function with a call for room 8
> Added olivers room 8

- game.c
made it so it prints my username
> Victor's lab 13 edit

- game.c
-Added room53 function to display name
> (Rick Garcia) Added room53 function

- game.c
lab 13, name function added for cscuser31(Yoonhong Min)
> Ymin lab13

- game.c
Added room for cscuser22 (Ryan A), hopefully this works out fine.
> Add: Room 22 added for future use

- game.c
Added a function that prints my username to room26.
> Added function to room26

- game.c
#UPDATE
Added CSC User 62 Room
> Add: Room 62

- game.c
(Anthony Morales)
#update
added my room/username so it prints name
> #update added my room and username so it prints my name

- game.c
Added function for user 58 for Steven
> Added room 58 for Steven

- game.c
> user36room

- game.c
> Jesse room 30

- game.c
I entered my username and created pull request for room 49
> I added my username to the github

- game.c
Added the function for Room 15.
> Add: Nicole with Room 15

- game.c
added my username and created a pull request
> Adding my username to the github.

- game.c
// Update
I added my room # function (#12) to the game.
>  Added: Room 12 - Santi

- game.c
This should be the addition for user 23.  If all goes well, it should work.
> Added text for user 23 (Fatoma Babonjo)

- game.c
Hello Professor,
This pulls request contains my work on Lab 13, I made changes to the " game.c " file including the necessary improvements discussed in class.
thank you very much.
> Add Aziz in room 48

- game.c
Reverts gpoppe/gitlabspring25#47
> Revert "Add room33game function and integrate into main game loop"

- game.c
- Implemented the logic for Room 27
> add: room 27 logic

- game.c
> Gerard McCallion Final Project

- game.c
Started with the intro part of my final project. room 37
> I Pedro added the intro of my final project

- game.c
update: first stages of room 16, began logic.
> J. Perez Moreno: Room 16 Update

- game.c
> Add: Room 61: Final RPG Game for Omar

- game.c
> Final project Completed

- game.c
Add game function for room 41 
Include 5 chests for user to choose from
Return user to main after choosing
> Final project for Henry Le

- game.c
I resynced and readded information. hope it works!
> Resynced fork Nicole Room 15

- game.c
> Yoonhong Min's final project

- game.c
made game about dinosaur keeper evading dinosaurs
> Luis Montanez (room3) Dinosaur keepr

- game.c
- Add Steven's RPG Game to the Pool : Room 58
- Add's 5 choices for the user to make, 
- look around the room, pick up an item, open a chest, check inventory, or leave through the door
- leaving through the door takes you back to the place where you choose rooms in the beginning.
- Added game references to my fav game minecraft, such as Notch Apple, Iron Sword, Diamond, and Torch to make it more legit.
- code was simple and pretty self explanatory, also used a char pointer.
> Steven's RPG Lair - Room 58

- game.c
> Reforked and Updated, Room51:Anthony

- game.c
This is for my final project for CSC 321 for Spring 2025. This is a survival horror game, if you pick my room number (62), the main function calls my function brentRoom.
> Brent Uyguangco's Room (62)

- game.c
Add my name that was not added in my merged PR #61
> Fix: Add Omar's Name

- game.c
> room 35, Raymond

- game.c
Added a Loop, Array, and Random Number. Special feature of using a while loop with 5 lives to ensure at least 5 choices are made, also uses a random number to determine choice multiple times.
> Room 25 Joel Castro Final Project Finale

- game.c
Added void functions room8parts1-5 for my portion of the game. The first three functions are decision trees with a random choice at the beginning(aided by a hint to get you to go to the next part of the game). There is a route one must take to get to the final functions that will complete the game. The route is {random number}, 3, 2, 1. The final function has a random aspect which is unique as a random decision will allow the user to view up to four different endings.
> Complete game for room8, Oliver Montero

- game.c
Special Feature is outlines around each text boxes to make the dialogue/steps more readable to the user.
> Alex Pham Room 56 final project

- game.c
It is basically a room where you take care of my bunny while I am running errands.. There is a loop, array, and randomized number included. I also added an ASCII image that reminds me of my bunny.
> Added my final project to room 2- Daira Aguilar

- game.c
> JoshR added room4 portion

- game.c
Completed my portion of the project for Room 38.
>  Room 38 Ryan Chavez

- game.c
added function prototype
added proper exit from break statement that will lead to my room
added separate function after main
> Jose Camacho Final Project added room14

- game.c
> Add Aziz room 48

- game.c
> Hubert's Final Project: Mr.Dice Casino

- game.c
adding my portion of the project room 37. - Pedro Nunez
> room 37 final game

- game.c
> Cameron added room 7 code

- game.c
This is the final pull for the project.  Everything should work.
> Final version (Fatoma)

- game.c
- Changed angelasRoom26 function
- Added checkChekhov and room26Encounter functions
- Added complete game code to Room 26
- Added my name to contributors
> Angela Jovanovic: Room 26 game fully completed - reforked

- game.c
Compiled with no issues, but hoping this works.
- Ryan A
> Add: Room 22 Added

- game.c
> adding my part

- game.c
Reverts gpoppe/gitlabspring25#131
> Revert "Room 16 Fix"

- game.c
Reverts gpoppe/gitlabspring25#128
> Revert "Add: Room 22 Added"

- game.c
I'm not sure what errors this had before, I did make a few edits to make it more readable. please let me know if there are any more.
> Add: Room 22

- game.c
Reverts gpoppe/gitlabspring25#144
> Revert "Add: Room 22"

- game.c
My portion to room 49 and my function, Victor Gonzalez
> My portion to room 49, Victor Gonzalez

- game.c
Added the far star trading post to the game
> Jake added room 11

- game.c
csc321 final proj - room 47 -  a kid  is trapped in a game, his goal is to figure out how to escape.
> room 47 - jessie f. csc321

- game.c
Room 16 'trigraph' warning fixed. However, the terminal shows warnings from other rooms.
> Room 16 Warning Fix
